# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache:
  - packages: true

warnings_are_errors: true
r_check_args: "--as-cran"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libglpk-dev

matrix:
  include:
  - r: release
    r_github_packages:
    - r-lib/covr
    after_success:
    - R CMD INSTALL $PKG_TARBALL
    - Rscript -e 'covr::coveralls()'
    - Rscript -e 'devtools::install(); devtools::test()'
  - r: devel

notifications:
  email:
    on_success: always
    on_failure: always
