# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

greedyMultDimSuppression <- function(dat, indices, subIndices, dimVars, verbose) {
    .Call('sdcTable_greedyMultDimSuppression', PACKAGE = 'sdcTable', dat, indices, subIndices, dimVars, verbose)
}

